server:
  port: 8090
spring:
  thymeleaf:
    #前缀，也就是模板存放的路径
    prefix: classpath:/templates/
    #编码格式
    encoding: UTF-8
    check-template-location: false
    #关闭缓存，不然无法看到实时页面
    cache: false
    #后缀
    suffix: .html
    #设置不严格的html
    mode: HTML
    servlet:
      content-type: text/html
  datasource:
    # druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/wanli?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    # 用户名、密码
    username: root
    password: ghp12345
  web:
    resources:
      static-locations: classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/templates/
#mybatis-plus配置
mybatis-plus:
  #dto别名映射
  type-aliases-package: com.ynu.wanli.user.dto
  #xml文件路径映射（xml文件要和接口文件同名）
  mapper-locations: com/ynu/wanli/user/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启日志
    map-underscore-to-camel-case: false
  # 全局变量配置
  # 逻辑删除-如：每个表中都有一个通用的字段isDelete描述当前数据是否被删除，1：已删除 0：未删除
#  global-config:
#    db-config:
#      # 当逻辑删除应该设置什么值：1
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#      logic-delete-field: isDelete